language: "python"

os:
  - "linux"

python:
  - "pypy"
  - "2.7"

install:
  # Install some tools for measuring code coverage and sending the results
  # to coveralls.
  - "pip install coveralls coverage"

  # Work-around the fact that Imaginary's setup.py requires Epsilon in order to
  # actually be imported. :/ Most likely we should just give up and use
  # setuptools at this point.
  - "pip install epsilon"

  # An "editable" install - which really just means a tweak to the environment
  # that makes the packages in the source checkout discoverable by the Python
  # import machinery.  It might eventually make sense to test an install which
  # actually tries to copy files into the right place.
  - "pip install -e ."

env:
  - "PYTHONPATH=ExampleGame"

script:
  - |
    echo "TRAVIS_PYTHON_VERSION=${TRAVIS_PYTHON_VERSION}"
    if [ ${TRAVIS_PYTHON_VERSION} == "pypy" ]; then
        $(type -p trial) --testmodule=imaginary/__init__.py
    else
        coverage run --branch --source=imaginary $(type -p trial) --testmodule=imaginary/__init__.py
    fi
  - |
    coverage report -m

after_success:
    - "coveralls"

notifications:
  email: false
