sudo: false

language: "python"

branches:
  only:
    - master

matrix:
  include:
    - python: "2.7"
    - python: "pypy"
      env: "PYENV_PYTHON=pypy-5.1"
    - python: "pypy"
      env: "SPHINX_TARGET=html" "PYENV_PYTHON=pypy-5.1"

install:
  # Upgrade PyPy to a recent version via pyenv, since the version on Travis is
  # often ancient.
  - |
    if [[ -n "${PYENV_PYTHON}" ]]; then
        if [[ "$DARWIN" == "true" ]]; then
            brew update;
            brew install pyenv || brew upgrade pyenv;
        else
            git clone https://github.com/yyuu/pyenv.git ~/.pyenv;
            PYENV_ROOT="$HOME/.pyenv";
            PATH="$PYENV_ROOT/bin:$PATH";
        fi
        eval "$(pyenv init -)";
        pyenv install "${PYENV_PYTHON}";
        pyenv global "${PYENV_PYTHON}";
        pyenv rehash;
    fi

  # Install some tools for measuring code coverage and sending the results
  # to coveralls.
  - |
    pip install coveralls coverage

  # An "editable" install - which really just means a tweak to the environment
  # that makes the packages in the source checkout discoverable by the Python
  # import machinery.  It might eventually make sense to test an install which
  # actually tries to copy files into the right place.
  - |
    if [ -v SPHINX_TARGET ]; then
        # As a bonus, if this build is going to do something with sphinx, drag
        # in any doc-related dependencies.
        pip install --editable .[doc]
    else
        pip install --editable .
        pip install --editable ExampleGame
    fi

script:
  - |
    if [ -v SPHINX_TARGET ]; then
        # This is a documentation-related build.
        make --directory=doc html
    elif [ ${TRAVIS_PYTHON_VERSION} == "pypy" ]; then
        # Skip coverage on pypy so the build doesn't take 15 minutes.
        $(type -p trial) --testmodule=imaginary/__init__.py
    else
        coverage run --branch --source=imaginary --omit=imaginary/pyparsing.py $(type -p trial) --testmodule=imaginary/__init__.py && coverage report -m
    fi

after_success:
  - |
    # Only submit coverage results for non-PyPy, non-Sphinx builds.
    if [ ! -v SPHINX_TARGET ] && [ ${TRAVIS_PYTHON_VERSION} != "pypy" ]; then
        coveralls
    fi

notifications:
  email: false
